CREATE EXTERNAL TABLE IF NOT EXISTS CLIENTES
(
    IDCLIENTE INT,
    CPF STRING,
    CNH STRING,
    VALIDADECNH STRING,
    NOME STRING,
    DATACADASTRO date,
    DATANASCIMENTO date,
    TELEFONE STRING,
    STATUS STRING
)
STORED AS PARQUET
LOCATION '/datalake/silver/clientes/';


CREATE EXTERNAL TABLE IF NOT EXISTS DESPACHANTES
(
    IDDESPACHANTE INT,
    NOME STRING,
    STATUS STRING,
    FILIAL STRING
)
STORED AS PARQUET
LOCATION '/datalake/silver/despachantes/';

CREATE EXTERNAL TABLE IF NOT EXISTS VEICULOS
(
    IDVEICULO INT,
    DATAAQUISICAO STRING,
    ANO INT,
    MODELO STRING,
    PLACA STRING,
    STATUS STRING,
    DIARIA STRING
) 
STORED AS PARQUET
LOCATION '/datalake/silver/veiculos/';

CREATE EXTERNAL TABLE IF NOT EXISTS LOCACAO
(
    IDLOCACAO INT,
    IDCLIENTE INT,
    IDDESPACHANTE INT,
    IDVEICULO INT,
    DATALOCACAO date,
    DATAENTREGA date,
    TOTAL STRING
)
STORED AS PARQUET
LOCATION '/datalake/silver/locacao/';

CREATE EXTERNAL TABLE IF NOT EXISTS CONTRATOS
(
    IDCONTRATO STRING,
    IDCLIENTE STRING,
    DATACADASTRO DATE,
    CONTRATO STRING
)
STORED AS PARQUET
LOCATION '/datalake/silver/contratos/';

CREATE EXTERNAL TABLE IF NOT EXISTS CONTRATOSSTREAM
(
    IDCONTRATO STRING,
    IDCLIENTE STRING,
    DATACADASTRO DATE,
    CONTRATO STRING
)
STORED AS PARQUET
LOCATION '/datalake/silver/contratosStream/';

CREATE EXTERNAL TABLE IF NOT EXISTS locacaoClientes
(
    ID INT,
    ANO INT,
    MES INT,
    TOTAL DOUBLE
)
STORED AS PARQUET
LOCATION '/datalake/gold/locacaoClientes/';

CREATE EXTERNAL TABLE IF NOT EXISTS contratosRisco
(
    ID STRING,
    IDCLIENTE STRING
)
STORED AS PARQUET
LOCATION '/datalake/gold/contratosRisco/';

CREATE EXTERNAL TABLE IF NOT EXISTS faturamento
(
    ANO INT,
    MES INT,
    TOTAL DOUBLE
)
STORED AS PARQUET
LOCATION '/datalake/gold/faturamento/';

CREATE EXTERNAL TABLE IF NOT EXISTS locacaoDespachantes
(
    ID INT,
    MODELO STRING,
    ANO INT,
    MES INT,
    TOTAL INT
)
STORED AS PARQUET
LOCATION '/datalake/gold/locacaoDespachantes/';

CREATE EXTERNAL TABLE IF NOT EXISTS locacaoVeiculos
(
    MODELO STRING,
    ANO INT,
    MES INT,
    TOTAL INT
)
STORED AS PARQUET
LOCATION '/datalake/gold/locacaoVeiculos/';

